name: aws-ts-k8s-nginx
runtime:
  name: nodejs
  options:
    packagemanager: npm
description: A minimal AWS TypeScript Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
