name: argocd
description: A TypeScript program to deploy a Helm chart onto a Kubernetes cluster
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: helm-kubernetes-typescript
